FROM golang:1.25-bookworm AS builder

WORKDIR /go/src/github.com/makkalot/eskit

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o /bin/camconfig ./services/camconfig/cmd/camconfig

FROM alpine:3.8

WORKDIR /app
COPY --from=builder /bin/camconfig /bin/camconfig
COPY ./services/camconfig/config.yaml .
COPY ./services/camconfig/web/templates ./web/templates

EXPOSE 8081
ENTRYPOINT ["/bin/camconfig"]