FROM golang:1.17-alpine3.7

RUN apk --no-cache add ca-certificates \
  && apk --no-cache add curl git bash gawk sed grep bc coreutils \
  && go get -u github.com/fullstorydev/grpcurl \
  && go install github.com/fullstorydev/grpcurl/... \
  && grpcurl --help