{
 "title": "Consumer Stream",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stream Inbound/s",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(application_id, partition_id)(rate(kiremit_events_stream_count[1m]))"
    }
   ]
  },
  {
   "title": "Stream Outbound/s",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(consumer_name)(rate(kiremit_consumers_consumed_count[1m]))"
    }
   ]
  },
  {
   "title": "Latest Stream Position",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kiremit_events_stream_last_id)"
    }
   ]
  },
  {
   "title": "Stream Position",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "kiremit_events_stream_last_id" }
   ]
  },
  {
   "title": "Inboud Stream Per/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kiremit_events_stream_count[1m])",
     "legendFormat": "{{partition_id}}"
    }
   ]
  },
  {
   "title": "Consumer Stream Position",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "kiremit_consumers_progress" }
   ]
  },
  {
   "title": "Consumer Stream Per/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kiremit_consumers_consumed_count[1m])",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Consumer Last Seen",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "kiremit_consumers_lastseen" }
   ]
  },
  {
   "title": "Stream Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * kiremit_consumers_progress / ignoring(consumer_name, group, instance, job) group_left sum without(partition_id, application_id, job, instance, group)(kiremit_events_stream_last_id)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  }
 ]
}