{
 "title": "Events",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "entity", "query": "kiremit_events_store_total" }
  ]
 },
 "panels": [
  {
   "title": "Total System Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kiremit_events_store_total)"
    }
   ]
  },
  {
   "title": "Avg System Events Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(event_type, entity_type)((rate(kiremit_events_store_total[1m])))"
    }
   ]
  },
  {
   "title": "Entity Total Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(event_type)(kiremit_events_store_total{entity_type=\"$entity\"})"
    }
   ]
  },
  {
   "title": "Entity Avg Events Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without(event_type)(rate(kiremit_events_store_total{entity_type=\"$entity\"}[1m]))"
    }
   ]
  },
  {
   "title": "EventStore Per/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(event_type)(rate(kiremit_events_store_total{entity_type=\"$entity\"}[1m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "EventStore Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kiremit_events_store_total{entity_type=\"$entity\"}[1m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Crud Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kiremit_events_crud_total{entity_type=\"$entity\"}[1m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "ListView Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kiremit_events_crud_listview{entity_type=\"$entity\"}[1m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}