{
 "title": "Grpc Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "grpc_server_started_total" }
  ]
 },
 "panels": [
  {
   "title": "Latency Unary ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handling_seconds_sum{grpc_service=\"$service\",grpc_type=\"unary\"}[1m])) * 1000/ sum by(grpc_method) (rate(grpc_server_handling_seconds_count{grpc_service=\"$service\",grpc_type=\"unary\"}[1m]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Inbound Rate/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_service=\"$service\"}[1m])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Outbound Rate/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_sent_total{grpc_service=\"$service\"}[1m])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Success Rate Req/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_service=\"$service\", grpc_code=\"OK\", grpc_type=\"unary\"}[1m])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate Req/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(grpc_code)(rate(grpc_server_handled_total{grpc_service=\"$service\", grpc_code!=\"OK\", grpc_type=\"unary\"}[1m]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  }
 ]
}