---
name: Build and Test Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: make build-compose-go
      - name: Test Go Services
        run: make test-compose-go


